### ISSUE TITLE
Application Crash on connection attempt

### ISSUE THREAD

**Issue by ks00908** [ddakebono/PalworldRcon#2]
### Description
When attempting to connect or test connetion to remote server application crashes without error message

### Steps to reproduce
1. Install application and required redistributable it asks for on start
2. Input server settings
3. attempt to test connection or connect to server

### Expected Result
Application connects allowing me to access commands on server

### Actual Result
Application crashes without error message.

### Enviroment

Client running application: Windows 10 Pro, 8GB ram

Server/Panel: Pterodactyl 1.11.5 instance with allocated ports: 25575, 8211 running palworld egg file by QuintenQVD0 (URL: https://gist.github.com/QuintenQVD0/8d7af6f08d716872ee609e9a203d696a ) with 16GB of RAM, 50GB HDD space

Server/Node: Pterodactyl Daemon v 1.11.8 instance hosted on dedicated server running ubuntu-18.04

**Comment by ddakebono** [comment]
I'll be looking into this later today, gonna be adding a console panel of some kind to display errors and allow of some level of debugging.

**Comment by ks00908** [comment]
> I'll be looking into this later today, gonna be adding a console panel of some kind to display errors and allow of some level of debugging.

i managed to track down exact reason for crash, it was because my config was slightly malformed on server so it didnt actually have RCON enabled (i had a newline entered by accident that i didnt spot when checking for errors first time)

once i fixed serverside config the application connected succesfully


I do however have minor Feature Request if its possible - Option to get Savefile ID of player to delete it if save gets corrupted instead of having to do gymnastics to find correct file.

**Comment by ddakebono** [comment]
Was gonna pop in here to get you to try out 1.1.0, but I see you solved the error lol

As for the request, unfortunately the rcon is extremely limited and doesn't give anything more then the name, some kind of character ID, and steamID of the users.

Version 1.1.0 fixes alot of crashing the tool had, so feel free to upgrade to it

https://github.com/ddakebono/PalworldRcon/releases/tag/1.1.0
