### ISSUE TITLE
.NET 8 Upgrade

### ISSUE THREAD

**Issue by LucHeart** [ddakebono/PalworldRcon#3]
Upgwade to .NET 8 bowno! There shouldn't be any code changes necessary :p

**Comment by ddakebono** [comment]
_I was lazy and didn't have the .net 8 SDK installed yet_

**Comment by ddakebono** [comment]
Upgraded to .Net 8 in 1.1.0

https://github.com/ddakebono/PalworldRcon/releases/tag/1.1.0
