### ISSUE TITLE
Can 'Send Notice' be used with utf-8?

### ISSUE THREAD

**Issue by eeldclf25** [ddakebono/PalworldRcon#4]
Hello.
I am operating a server that uses Korean, but unfortunately, Korean does not work in Send Notice.
Is there a solution to this issue?

**Comment by ddakebono** [comment]
You can try using the 1.1.0 console tab and see if using Broadcast from there can send it, I'm handling the encoding as UTF-8 so it should all be working on my tools side, however I'm not sure if the servers rcon plays nice with it.

There's been quite a few strange issues with the rcon, so hard to say what's going funky.

**Comment by eeldclf25** [comment]
Thank you.

Upon checking, it seems that the game RCON library can only receive data as ascii.

Related URL:
https://developer.valvesoftware.com/wiki/Source_RCON_Protocol#Basic_Packet_Structure
