### ISSUE TITLE
unban ?

### ISSUE THREAD

**Issue by josigamer** [ddakebono/PalworldRcon#5]
how to remove the ban?
it only has the ban button

where are banned ids saved on the server?

**Comment by ddakebono** [comment]
Unfortunately there is no unban command either in game or through rcon, the only way to unban a user is to go to the ban list stored in your save and remove them. 

I haven't had to ban anyone so I'm not entirely sure where the file is but I believe it appears in the world save in Pal/Saved/SaveGames/0/NUMBERS in your dedicated server install.
