### ISSUE TITLE
Can you write it php or nodejs?

### ISSUE THREAD

**Issue by blackcatxt** [ddakebono/PalworldRcon#9]
Can you write it php or nodejs?

**Comment by ddakebono** [comment]
Sorry but that is out of the scope for this project, while I do some work in PHP I have 0 interest in writing an rcon tool in PHP.

This project is intended for specifically a desktop tool for interacting with the Palworld Rcon.

**Comment by blackcatxt** [comment]
One server has a website, I think php rcon can get the list of players. That's also a great thing
